module.exports = {
	rules: {
		// Possible error
		'getter-return': [1, { 'allowImplicit': true }],
		'no-compare-neg-zero': [1],
		'no-cond-assign': [1],
		'no-constant-condition': [1],
		'no-dupe-args': [2],
		'no-dupe-keys': [2],
		'no-duplicate-case': [2],
		'no-empty': [1],
		'no-empty-character-class': [1],
		'no-ex-assign': [1],
		'no-extra-boolean-cast': [1],
		'no-extra-semi': [1],
		'no-func-assign': [1],
		'no-invalid-regexp': [1, {'allowConstructorFlags': ['u', 'y']}],
		'no-irregular-whitespace': [1],
		'no-obj-calls': [1],
		'no-regex-spaces': [1],
		'no-unexpected-multiline': [1],
		'no-unreachable': [2],
		'use-isnan': [1],
		'valid-typeof': [1],
		'no-else-return': [1],
		'no-extra-bind': [1],
		'no-extra-label': [1],
		'no-fallthrough': [1],
		'no-multi-spaces': [1],
		'no-redeclare': [2, {builtinGlobals: true}],
		'no-self-compare': [1],
		'no-useless-call': [1],
		'no-useless-concat': [1],
		'no-useless-escape': [1],
		'no-unused-vars': [1],
		'no-use-before-define': [1],
		// Stylistic Issues
		'func-call-spacing': [1],
		// ECMAScript 6
		'constructor-super': [2],
		'no-class-assign': [2],
		'no-const-assign': [2],
		'no-dupe-class-members': [2],
		'no-duplicate-imports': [1],
		'no-this-before-super': [2],
		'no-useless-computed-key': [1],
		'no-useless-constructor': [1],
		'no-useless-rename': [1],
	}
}